apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: <%= @name %>
  annotations:
    volume.beta.kubernetes.io/storage-class: <%= @sc_name %>
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
