apiVersion: v1
kind: Pod
metadata:
  name: <%= @name %>
  labels:
    name: <%= @name %>
spec:
  restartPolicy: Never
  containers:
    - env:
      - name: RESPONSE
        value: "Hello World!"
      - resources:
        limits :
          cpu: 0.5
        image: openshift/hello-openshift
        name: che
        ports:
          - containerPort: 8080
            name: http
